### ISSUE TITLE
Add Remove/ Delete method into Binary Search Tree.

### ISSUE THREAD

**Issue by yenkhoon** [pactus-project/kelk#51]
### Describe the problem you'd like to have solved
Removing record from BST

Currently there is no method to delete or remove the key from BST.

### Describe the ideal solution
Able to delete or removing by providing a key.

## Alternatives and current work-arounds
If we insist not to have remove/ delete method in BST, in future all the smart contract has to be designed the keys are not disposable.

**Comment by b00f** [comment]
@yenkhoon please check the #52 . I wrote some test to check the `remove` function. It should work.

**Comment by yenkhoon** [comment]
closing this as the feature already merged!
